# Generated by Django 5.2.4 on 2025-07-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_fooditemsmodel_resturant_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditemsmodel',
            old_name='resturant_owner',
            new_name='restaurant_owner',
        ),
        migrations.AddField(
            model_name='fooditemsmodel',
            name='admin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
